### ISSUE TITLE
Cannot find extra libraries! Exiting!

### ISSUE THREAD

**Issue by troyBORG** [RileyGuy/Cumulo#2]
I extracted the zip file into:
`~/Steam/steamapps/common/Resonite/Headless`

If I cd back to `~/Steam/steamapps/common/Resonite` I can run 

mono ./Cumulo.exe ~/Steam/steamapps/common/Resonite/Headless

```
steam@ResoniteServer:~/Steam/steamapps/common/Resonite$ mono ./Cumulo.exe ~/Steam/steamapps/common/Resonite/Headless
[INFO] Starting Cumulo patcher!

--------
You are about to apply Cumulo patches to "/home/steam/Steam/steamapps/common/Resonite/Headless".
This operation is NOT reversible and will make your
headless server incompatible with Mono/.NET Framework
in order to support .NET 8.
--------

Do you want to continue? (y/N):
```

But if I go into the Headless folder and try to it back a folder with..

`mono .././Cumulo.exe ~/Steam/steamapps/common/Resonite/Headless`

```
steam@ResoniteServer:~/Steam/steamapps/common/Resonite/Headless$ mono .././Cumulo.exe ~/Steam/steamapps/common/Resonite/
Headless
[INFO] Starting Cumulo patcher!
[ERROR] Cannot find extra libraries! Exiting!
```

every update for Resonite I have to run the patcher again or I error out.
Its annoying that I can just script it as part of  my StartHeadless.sh

**Comment by BlueCyro** [comment]
The working directory needs to be the folder Cumulo is in (e.g. you need to `cd` in your script to the correct dirs). I specifically made it so that it can be added as part of a startup/update script.

You need to do something along the lines of:

```bash
#!/bin/bash
cd path/to/your/cumulo/install
mono ./Cumulo.exe path/to/your/headless --noconfirm
cd path/to/your/headless
dotnet Resonite.exe -your -launch -arguments -here
```
